### ISSUE TITLE
kolor status bara

### ISSUE THREAD

**Issue by k-rokicki** [k-rokicki/BUWing#20]
`BUWing/app/src/main/res/values/colors.xml` jest do zmiany - w 68136c4d673e784e96d86472b321cd1d75a72038 ustawiliśmy tam kolory do listy zaproszeń, trzeba gdzieś indziej bo `colorPrimaryDark` zmienia kolor status bara

**Comment by mkozlowski98** [comment]
zdefiniowałem oddzielne kolory dla przycisków w liście zaproszeń i znajomych więc możemy ustawić colorPrimaryDark na jaki chcemy
